[package]
name = "pokerole-discord-bot"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serenity = { version = "0.11.7", default-features = false, features = ["builder", "cache"] }
poise = "0.5.7"
tokio = { version  = "1.33.0", features = ["rt-multi-thread"] }
csv = "1.3.0"
serde = { version = "1.0.192", features = ["derive"] }
serde_json = "1.0.108"
serde_with = "3.4.0"
futures = { version = "0.3.29", default-features = false }
log = "0.4.20"
env_logger = "0.10.0"
rand = { version = "0.8.5", features = ["alloc"] }
strum = "0.25.0"
strum_macros = "0.25.3"
chrono = "0.4.31"
sqlx = { version = "0.7.2", features = ["runtime-tokio-rustls", "sqlite", "chrono"] }
regex = "1.10.2"
more-asserts = "0.3.1"
