[package]
name = "pokerole-discord-bot"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serenity = { version = "0.11.6", default-features = false, features = ["builder", "cache"] }
poise = "0.5.5"
tokio = { version  = "1.28.2", features = ["rt-multi-thread"] }
csv = "1.2.1"
serde = { version = "1.0.163", features = ["derive"] }
serde_json = "1.0.96"
serde_with = "3.3.0"
futures = { version = "0.3.28", default-features = false }
log = "0.4.18"
env_logger = "0.10.0"
rand = { version = "0.8.5", features = ["alloc"] }
strum = "0.25.0"
strum_macros = "0.25.1"
chrono = "0.4.26"
sqlx = { version = "0.7.1", features = ["runtime-tokio-rustls", "sqlite", "chrono"] }
regex = "1.8.4"
more-asserts = "0.3.1"
